CREATE TABLE `alumno` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(250) NOT NULL,
  `APELLIDO_1` varchar(250) NOT NULL,
  `APELLIDO_2` varchar(250) NOT NULL
);
ALTER TABLE `alumno`
  ADD PRIMARY KEY (`ID`);
INSERT INTO ALUMNO VALUES (1, 'Carlos', 'Padilla', 'Diaz');




CREATE TABLE `profesor` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(250) NOT NULL,
  `APELLIDO_1` varchar(250) NOT NULL,
  `APELLIDO_2` varchar(250) NOT NULL,
  `FECHA_ALTA` date
);
ALTER TABLE `profesor`
  ADD PRIMARY KEY (`ID`);
INSERT INTO PROFESOR VALUES (1, 'Jacinto', 'Garcia', 'Perez', DATE '2019-03-16');
INSERT INTO PROFESOR VALUES (2, 'Mateo', 'Lopez', 'Gomez', DATE '2019-03-16');




CREATE TABLE `materia` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(250) NOT NULL
);
ALTER TABLE `materia`
  ADD PRIMARY KEY (`ID`);
INSERT INTO MATERIA VALUES (1,'Matematicas');
INSERT INTO MATERIA VALUES (2,'Lengua');
INSERT INTO MATERIA VALUES (3,'Ingles');





CREATE TABLE `profesor_materia` (
  `ID_PROFESOR` int(11) NOT NULL,
   `ID_MATERIA` int(11) NOT NULL
);
ALTER TABLE `profesor_materia`
  ADD PRIMARY KEY (`ID_PROFESOR`, `ID_MATERIA`);
INSERT INTO PROFESOR_MATERIA VALUES (1,1);
INSERT INTO PROFESOR_MATERIA VALUES (1,2);
INSERT INTO PROFESOR_MATERIA VALUES (2,3);




COMMIT;

